package model;
// Generated 23/06/2016 06:10:51 AM by Hibernate Tools 4.3.1



/**
 * Paises generated by hbm2java
 */
public class Paises  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private int valor;

    public Paises() {
    }

    public Paises(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public int getValor() {
        return valor;
    }

    public void setValor(int valor) {
        this.valor = valor;
    }




}


